#!/usr/bin/env python

Import('env')
Import('env_modules')
import glob

thirdparty_base_dir = '#thirdparty/taglib/'
thirdparty_dirs = [
    '',
    '3rdparty/',
    'ape/',
    'asf/',
    'flac/',
    'it/',
    'mod/',
    'mp4/',
    'mpc/',
    'mpeg/',
    'mpeg/id3v1/',
    'mpeg/id3v2/',
    'mpeg/id3v2/frames/',
    'ogg/',
    'ogg/flac/',
    'ogg/opus/',
    'ogg/speex/',
    'ogg/vorbis/',
    'riff/',
    'riff/aiff/',
    'riff/wav/',
    's3m/',
    'toolkit/',
    'trueaudio/',
    'wavpack/',
    'xm/'
]

thirdparty_sources = []
for thirdparty_dir in thirdparty_dirs:
    thirdparty_sources.extend(Glob(thirdparty_base_dir + thirdparty_dir + '*.cpp'))

env_taglib = env_modules.Clone()
env_taglib.Prepend(CPPPATH = [thirdparty_base_dir + thirdparty_dir for thirdparty_dir in thirdparty_dirs])

env_thirdparty = env_taglib.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(env.modules_sources, thirdparty_sources)
env_thirdparty.Append(CXXFLAGS=['-DTAGLIB_STATIC'])

env_taglib.add_source_files(env.modules_sources, "*.cpp")

#env_taglib.ParseConfig('pkg-config --cflags --libs taglib')
env_taglib.Append(CXXFLAGS=['-DTAGLIB_STATIC'])

# needed so it actually gets linked
#env.ParseConfig('pkg-config --libs taglib')